#!/usr/bin/env bash
set -e

# Wrapper script for Babashka that downloads and installs the
# executable if not present, and removes backslashes at the end of
# lines.

CURDIR=$(cd $(dirname "$0") && pwd)
BB=$CURDIR/../bin/bb
if ! [ -e $BB ]; then
	mkdir -p $CURDIR
	pushd $CURDIR
	case "$(uname -m)" in
		x86_64)
			tar_file=babashka-1.3.186-macos-amd64.tar.gz
			;;
		aarch64|arm64)
			tar_file=babashka-1.3.186-macos-aarch64.tar.gz
			;;
		*)
			echo "Unsupported architecture: $(uname -m)" >&2
			exit 1
			;;
	esac
	curl -sLO "https://github.com/babashka/babashka/releases/download/v1.3.186/$tar_file"
	cat $tar_file.sha512 | shasum --check
	mkdir tmp
	tar -xzf $tar_file -C tmp
	rm $tar_file
	mkdir -p $(dirname $BB)
	mv tmp/bb $(dirname $BB)
	rm -r tmp
	popd
fi
code="$1"
if [[ $code == -c ]]; then
	# This probably happens because we are not using GNU Make >= 3.82
	# Work around this by ignoring the -c argument
	shift
	code="$1"
fi
code=$(echo "$code" | sed 's/ *\\$//g')
$BB --config $CURDIR/bb.edn "$code"
